#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /ncs-station-finder/src/
COPY pom.xml /ncs-station-finder
RUN mvn -f /ncs-station-finder/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build /ncs-station-finder/target/demo-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]